// This file was automatically generated by the Soy compiler.
// Please don't edit this file by hand.

package com.google.template.soy.examples;

import com.google.common.collect.ImmutableMap;
import com.google.common.collect.ImmutableSet;
import com.google.template.soy.parseinfo.SoyFileInfo;
import com.google.template.soy.parseinfo.SoyTemplateInfo;


/**
 * Soy parse info for features.soy.
 *
 * @deprecated Use {@link com.google.template.soy.examples.FeaturesTemplates} instead. See go/soy-java-type-safe.
 */
@Deprecated
public final class FeaturesSoyInfo extends SoyFileInfo {


  /** This Soy file's namespace. */
  public static final String __NAMESPACE__ = "soy.examples.features";


  @Deprecated
  public static final class TemplateName {
    private TemplateName() {}

    /** The full template name of the .demoComments template. */
    public static final String DEMO_COMMENTS = "soy.examples.features.demoComments";
    public static final com.google.template.soy.parseinfo.TemplateName DEMO_COMMENTS__NAME = com.google.template.soy.parseinfo.TemplateName.of(DEMO_COMMENTS);
    /** The full template name of the .demoLineJoining template. */
    public static final String DEMO_LINE_JOINING = "soy.examples.features.demoLineJoining";
    public static final com.google.template.soy.parseinfo.TemplateName DEMO_LINE_JOINING__NAME = com.google.template.soy.parseinfo.TemplateName.of(DEMO_LINE_JOINING);
    /** The full template name of the .demoRawTextCommands template. */
    public static final String DEMO_RAW_TEXT_COMMANDS = "soy.examples.features.demoRawTextCommands";
    public static final com.google.template.soy.parseinfo.TemplateName DEMO_RAW_TEXT_COMMANDS__NAME = com.google.template.soy.parseinfo.TemplateName.of(DEMO_RAW_TEXT_COMMANDS);
    /** The full template name of the .demoPrint template. */
    public static final String DEMO_PRINT = "soy.examples.features.demoPrint";
    public static final com.google.template.soy.parseinfo.TemplateName DEMO_PRINT__NAME = com.google.template.soy.parseinfo.TemplateName.of(DEMO_PRINT);
    /** The full template name of the .demoAutoescapeTrue template. */
    public static final String DEMO_AUTOESCAPE_TRUE = "soy.examples.features.demoAutoescapeTrue";
    public static final com.google.template.soy.parseinfo.TemplateName DEMO_AUTOESCAPE_TRUE__NAME = com.google.template.soy.parseinfo.TemplateName.of(DEMO_AUTOESCAPE_TRUE);
    /** The full template name of the .demoMsg template. */
    public static final String DEMO_MSG = "soy.examples.features.demoMsg";
    public static final com.google.template.soy.parseinfo.TemplateName DEMO_MSG__NAME = com.google.template.soy.parseinfo.TemplateName.of(DEMO_MSG);
    /** The full template name of the .demoIf template. */
    public static final String DEMO_IF = "soy.examples.features.demoIf";
    public static final com.google.template.soy.parseinfo.TemplateName DEMO_IF__NAME = com.google.template.soy.parseinfo.TemplateName.of(DEMO_IF);
    /** The full template name of the .demoSwitch template. */
    public static final String DEMO_SWITCH = "soy.examples.features.demoSwitch";
    public static final com.google.template.soy.parseinfo.TemplateName DEMO_SWITCH__NAME = com.google.template.soy.parseinfo.TemplateName.of(DEMO_SWITCH);
    /** The full template name of the .demoFor template. */
    public static final String DEMO_FOR = "soy.examples.features.demoFor";
    public static final com.google.template.soy.parseinfo.TemplateName DEMO_FOR__NAME = com.google.template.soy.parseinfo.TemplateName.of(DEMO_FOR);
    /** The full template name of the .demoFor_Range template. */
    public static final String DEMO_FOR_RANGE = "soy.examples.features.demoFor_Range";
    public static final com.google.template.soy.parseinfo.TemplateName DEMO_FOR_RANGE__NAME = com.google.template.soy.parseinfo.TemplateName.of(DEMO_FOR_RANGE);
    /** The full template name of the .demoCallWithoutParam template. */
    public static final String DEMO_CALL_WITHOUT_PARAM = "soy.examples.features.demoCallWithoutParam";
    public static final com.google.template.soy.parseinfo.TemplateName DEMO_CALL_WITHOUT_PARAM__NAME = com.google.template.soy.parseinfo.TemplateName.of(DEMO_CALL_WITHOUT_PARAM);
    /** The full template name of the .demoCallOtherFile template. */
    public static final String DEMO_CALL_OTHER_FILE = "soy.examples.features.demoCallOtherFile";
    public static final com.google.template.soy.parseinfo.TemplateName DEMO_CALL_OTHER_FILE__NAME = com.google.template.soy.parseinfo.TemplateName.of(DEMO_CALL_OTHER_FILE);
    /** The full template name of the .demoCallWithParam template. */
    public static final String DEMO_CALL_WITH_PARAM = "soy.examples.features.demoCallWithParam";
    public static final com.google.template.soy.parseinfo.TemplateName DEMO_CALL_WITH_PARAM__NAME = com.google.template.soy.parseinfo.TemplateName.of(DEMO_CALL_WITH_PARAM);
    /** The full template name of the .demoCallWithParamBlock template. */
    public static final String DEMO_CALL_WITH_PARAM_BLOCK = "soy.examples.features.demoCallWithParamBlock";
    public static final com.google.template.soy.parseinfo.TemplateName DEMO_CALL_WITH_PARAM_BLOCK__NAME = com.google.template.soy.parseinfo.TemplateName.of(DEMO_CALL_WITH_PARAM_BLOCK);
    /** The full template name of the .demoParamWithKindAttribute template. */
    public static final String DEMO_PARAM_WITH_KIND_ATTRIBUTE = "soy.examples.features.demoParamWithKindAttribute";
    public static final com.google.template.soy.parseinfo.TemplateName DEMO_PARAM_WITH_KIND_ATTRIBUTE__NAME = com.google.template.soy.parseinfo.TemplateName.of(DEMO_PARAM_WITH_KIND_ATTRIBUTE);
    /** The full template name of the .demoExpressions template. */
    public static final String DEMO_EXPRESSIONS = "soy.examples.features.demoExpressions";
    public static final com.google.template.soy.parseinfo.TemplateName DEMO_EXPRESSIONS__NAME = com.google.template.soy.parseinfo.TemplateName.of(DEMO_EXPRESSIONS);
    /** The full template name of the .demoDoubleBraces template. */
    public static final String DEMO_DOUBLE_BRACES = "soy.examples.features.demoDoubleBraces";
    public static final com.google.template.soy.parseinfo.TemplateName DEMO_DOUBLE_BRACES__NAME = com.google.template.soy.parseinfo.TemplateName.of(DEMO_DOUBLE_BRACES);
    /** The full template name of the .demoBidiSupport template. */
    public static final String DEMO_BIDI_SUPPORT = "soy.examples.features.demoBidiSupport";
    public static final com.google.template.soy.parseinfo.TemplateName DEMO_BIDI_SUPPORT__NAME = com.google.template.soy.parseinfo.TemplateName.of(DEMO_BIDI_SUPPORT);
    /** The full template name of the .bidiGlobalDir template. */
    public static final String BIDI_GLOBAL_DIR = "soy.examples.features.bidiGlobalDir";
    public static final com.google.template.soy.parseinfo.TemplateName BIDI_GLOBAL_DIR__NAME = com.google.template.soy.parseinfo.TemplateName.of(BIDI_GLOBAL_DIR);
    /** The full template name of the .exampleHeader template. */
    public static final String EXAMPLE_HEADER = "soy.examples.features.exampleHeader";
    public static final com.google.template.soy.parseinfo.TemplateName EXAMPLE_HEADER__NAME = com.google.template.soy.parseinfo.TemplateName.of(EXAMPLE_HEADER);
  }


  /**
   * Param names from all templates in this Soy file.
   */
  @Deprecated
  public static final class Param {
    private Param() {}

    /** Listed by .demoBidiSupport. */
    public static final String AUTHOR = "author";
    /** Listed by .demoPrint. */
    public static final String BOO = "boo";
    /** Listed by .demoCallWithParam. */
    public static final String COMPANION_NAME = "companionName";
    /** Listed by .demoExpressions. */
    public static final String CURRENT_YEAR = "currentYear";
    /** Listed by .tripReport_ (private). */
    public static final String DESTINATION = "destination";
    /** Listed by .demoCallWithParam. */
    public static final String DESTINATIONS = "destinations";
    /** Listed by .exampleHeader. */
    public static final String EXAMPLE_NAME = "exampleName";
    /** Listed by .exampleHeader. */
    public static final String EXAMPLE_NUM = "exampleNum";
    /** Listed by .demoAutoescapeTrue. */
    public static final String ITALIC_HTML = "italicHtml";
    /** Listed by .buildCommaSeparatedList_ (private). */
    public static final String ITEMS = "items";
    /** Listed by .demoBidiSupport. */
    public static final String KEYWORDS = "keywords";
    /** Listed by .demoParamWithKindAttribute. */
    public static final String LIST = "list";
    /** Listed by .demoParamWithKindAttributeCallee_ (private). */
    public static final String LIST_ITEMS = "listItems";
    /** Listed by .demoParamWithKindAttribute, .demoParamWithKindAttributeCallee_ (private). */
    public static final String MESSAGE = "message";
    /**
     * Listed by .demoMsg, .demoSwitch, .demoCallWithoutParam, .demoCallWithParam,
     * .demoCallWithParamBlock, .tripReport_ (private).
     */
    public static final String NAME = "name";
    /** Listed by .demoFor_Range. */
    public static final String NUM_LINES = "numLines";
    /** Listed by .demoFor. */
    public static final String PERSONS = "persons";
    /** Listed by .demoIf. */
    public static final String PI = "pi";
    /** Listed by .demoDoubleBraces. */
    public static final String SET_MEMBERS = "setMembers";
    /** Listed by .demoDoubleBraces. */
    public static final String SET_NAME = "setName";
    /** Listed by .demoExpressions. */
    public static final String STUDENTS = "students";
    /** Listed by .demoBidiSupport. */
    public static final String TITLE = "title";
    /** Listed by .demoCallWithoutParam. */
    public static final String TRIP_INFO = "tripInfo";
    /** Listed by .demoPrint. */
    public static final String TWO = "two";
    /** Listed by .demoBidiSupport. */
    public static final String YEAR = "year";
  }


  /**
   * Demo comments.
   * 
   * @deprecated Use {@link com.google.template.soy.examples.FeaturesTemplates.DemoComments} instead. See go/soy-java-type-safe.
   */
  @Deprecated
  public static final class DemoCommentsSoyTemplateInfo extends SoyTemplateInfo {

    /** This template's full name. */
    public static final String __NAME__ = TemplateName.DEMO_COMMENTS;
    private static final com.google.template.soy.parseinfo.TemplateName __TEMPLATE_NAME__ = TemplateName.DEMO_COMMENTS__NAME;

    private DemoCommentsSoyTemplateInfo() {
      super(
          __NAME__,
          __TEMPLATE_NAME__,
          ImmutableMap.<String, ParamRequisiteness>of());
    }

    private static final DemoCommentsSoyTemplateInfo __INSTANCE__ =
        new DemoCommentsSoyTemplateInfo();

    public static DemoCommentsSoyTemplateInfo getInstance() {
      return __INSTANCE__;
    }
  }

  /** Same as DemoCommentsSoyTemplateInfo.getInstance(). */
  @Deprecated
  public static final DemoCommentsSoyTemplateInfo DEMO_COMMENTS =
      DemoCommentsSoyTemplateInfo.getInstance();


  /**
   * Demo line joining.
   * 
   * @deprecated Use {@link com.google.template.soy.examples.FeaturesTemplates.DemoLineJoining} instead. See go/soy-java-type-safe.
   */
  @Deprecated
  public static final class DemoLineJoiningSoyTemplateInfo extends SoyTemplateInfo {

    /** This template's full name. */
    public static final String __NAME__ = TemplateName.DEMO_LINE_JOINING;
    private static final com.google.template.soy.parseinfo.TemplateName __TEMPLATE_NAME__ = TemplateName.DEMO_LINE_JOINING__NAME;

    private DemoLineJoiningSoyTemplateInfo() {
      super(
          __NAME__,
          __TEMPLATE_NAME__,
          ImmutableMap.<String, ParamRequisiteness>of());
    }

    private static final DemoLineJoiningSoyTemplateInfo __INSTANCE__ =
        new DemoLineJoiningSoyTemplateInfo();

    public static DemoLineJoiningSoyTemplateInfo getInstance() {
      return __INSTANCE__;
    }
  }

  /** Same as DemoLineJoiningSoyTemplateInfo.getInstance(). */
  @Deprecated
  public static final DemoLineJoiningSoyTemplateInfo DEMO_LINE_JOINING =
      DemoLineJoiningSoyTemplateInfo.getInstance();


  /**
   * Demo raw text commands.
   * 
   * @deprecated Use {@link com.google.template.soy.examples.FeaturesTemplates.DemoRawTextCommands} instead. See go/soy-java-type-safe.
   */
  @Deprecated
  public static final class DemoRawTextCommandsSoyTemplateInfo extends SoyTemplateInfo {

    /** This template's full name. */
    public static final String __NAME__ = TemplateName.DEMO_RAW_TEXT_COMMANDS;
    private static final com.google.template.soy.parseinfo.TemplateName __TEMPLATE_NAME__ = TemplateName.DEMO_RAW_TEXT_COMMANDS__NAME;

    private DemoRawTextCommandsSoyTemplateInfo() {
      super(
          __NAME__,
          __TEMPLATE_NAME__,
          ImmutableMap.<String, ParamRequisiteness>of());
    }

    private static final DemoRawTextCommandsSoyTemplateInfo __INSTANCE__ =
        new DemoRawTextCommandsSoyTemplateInfo();

    public static DemoRawTextCommandsSoyTemplateInfo getInstance() {
      return __INSTANCE__;
    }
  }

  /** Same as DemoRawTextCommandsSoyTemplateInfo.getInstance(). */
  @Deprecated
  public static final DemoRawTextCommandsSoyTemplateInfo DEMO_RAW_TEXT_COMMANDS =
      DemoRawTextCommandsSoyTemplateInfo.getInstance();


  /**
   * Demo 'print'.
   * 
   * @deprecated Use {@link com.google.template.soy.examples.FeaturesTemplates.DemoPrint} instead. See go/soy-java-type-safe.
   */
  @Deprecated
  public static final class DemoPrintSoyTemplateInfo extends SoyTemplateInfo {

    /** This template's full name. */
    public static final String __NAME__ = TemplateName.DEMO_PRINT;
    private static final com.google.template.soy.parseinfo.TemplateName __TEMPLATE_NAME__ = TemplateName.DEMO_PRINT__NAME;

    /** Something scary. */
    public static final String BOO = Param.BOO;
    /** Preferably the number 2. */
    public static final String TWO = Param.TWO;

    private DemoPrintSoyTemplateInfo() {
      super(
          __NAME__,
          __TEMPLATE_NAME__,
          com.google.common.collect.ImmutableMap.<String, ParamRequisiteness>builder()
              .put(BOO, ParamRequisiteness.REQUIRED)
              .put(TWO, ParamRequisiteness.REQUIRED)
              .build());
    }

    private static final DemoPrintSoyTemplateInfo __INSTANCE__ =
        new DemoPrintSoyTemplateInfo();

    public static DemoPrintSoyTemplateInfo getInstance() {
      return __INSTANCE__;
    }
  }

  /** Same as DemoPrintSoyTemplateInfo.getInstance(). */
  @Deprecated
  public static final DemoPrintSoyTemplateInfo DEMO_PRINT =
      DemoPrintSoyTemplateInfo.getInstance();


  /**
   * Demo autoescape true.
   * 
   * @deprecated Use {@link com.google.template.soy.examples.FeaturesTemplates.DemoAutoescapeTrue} instead. See go/soy-java-type-safe.
   */
  @Deprecated
  public static final class DemoAutoescapeTrueSoyTemplateInfo extends SoyTemplateInfo {

    /** This template's full name. */
    public static final String __NAME__ = TemplateName.DEMO_AUTOESCAPE_TRUE;
    private static final com.google.template.soy.parseinfo.TemplateName __TEMPLATE_NAME__ = TemplateName.DEMO_AUTOESCAPE_TRUE__NAME;

    public static final String ITALIC_HTML = Param.ITALIC_HTML;

    private DemoAutoescapeTrueSoyTemplateInfo() {
      super(
          __NAME__,
          __TEMPLATE_NAME__,
          com.google.common.collect.ImmutableMap.<String, ParamRequisiteness>builder()
              .put(ITALIC_HTML, ParamRequisiteness.REQUIRED)
              .build());
    }

    private static final DemoAutoescapeTrueSoyTemplateInfo __INSTANCE__ =
        new DemoAutoescapeTrueSoyTemplateInfo();

    public static DemoAutoescapeTrueSoyTemplateInfo getInstance() {
      return __INSTANCE__;
    }
  }

  /** Same as DemoAutoescapeTrueSoyTemplateInfo.getInstance(). */
  @Deprecated
  public static final DemoAutoescapeTrueSoyTemplateInfo DEMO_AUTOESCAPE_TRUE =
      DemoAutoescapeTrueSoyTemplateInfo.getInstance();


  /**
   * Demo 'msg'.
   * 
   * @deprecated Use {@link com.google.template.soy.examples.FeaturesTemplates.DemoMsg} instead. See go/soy-java-type-safe.
   */
  @Deprecated
  public static final class DemoMsgSoyTemplateInfo extends SoyTemplateInfo {

    /** This template's full name. */
    public static final String __NAME__ = TemplateName.DEMO_MSG;
    private static final com.google.template.soy.parseinfo.TemplateName __TEMPLATE_NAME__ = TemplateName.DEMO_MSG__NAME;

    /** The name of the person to say hello to. */
    public static final String NAME = Param.NAME;

    private DemoMsgSoyTemplateInfo() {
      super(
          __NAME__,
          __TEMPLATE_NAME__,
          com.google.common.collect.ImmutableMap.<String, ParamRequisiteness>builder()
              .put(NAME, ParamRequisiteness.REQUIRED)
              .build());
    }

    private static final DemoMsgSoyTemplateInfo __INSTANCE__ =
        new DemoMsgSoyTemplateInfo();

    public static DemoMsgSoyTemplateInfo getInstance() {
      return __INSTANCE__;
    }
  }

  /** Same as DemoMsgSoyTemplateInfo.getInstance(). */
  @Deprecated
  public static final DemoMsgSoyTemplateInfo DEMO_MSG =
      DemoMsgSoyTemplateInfo.getInstance();


  /**
   * Demo 'if'.
   * 
   * @deprecated Use {@link com.google.template.soy.examples.FeaturesTemplates.DemoIf} instead. See go/soy-java-type-safe.
   */
  @Deprecated
  public static final class DemoIfSoyTemplateInfo extends SoyTemplateInfo {

    /** This template's full name. */
    public static final String __NAME__ = TemplateName.DEMO_IF;
    private static final com.google.template.soy.parseinfo.TemplateName __TEMPLATE_NAME__ = TemplateName.DEMO_IF__NAME;

    /** An approximate value for pi. */
    public static final String PI = Param.PI;

    private DemoIfSoyTemplateInfo() {
      super(
          __NAME__,
          __TEMPLATE_NAME__,
          com.google.common.collect.ImmutableMap.<String, ParamRequisiteness>builder()
              .put(PI, ParamRequisiteness.REQUIRED)
              .build());
    }

    private static final DemoIfSoyTemplateInfo __INSTANCE__ =
        new DemoIfSoyTemplateInfo();

    public static DemoIfSoyTemplateInfo getInstance() {
      return __INSTANCE__;
    }
  }

  /** Same as DemoIfSoyTemplateInfo.getInstance(). */
  @Deprecated
  public static final DemoIfSoyTemplateInfo DEMO_IF =
      DemoIfSoyTemplateInfo.getInstance();


  /**
   * Demo 'switch'.
   * 
   * @deprecated Use {@link com.google.template.soy.examples.FeaturesTemplates.DemoSwitch} instead. See go/soy-java-type-safe.
   */
  @Deprecated
  public static final class DemoSwitchSoyTemplateInfo extends SoyTemplateInfo {

    /** This template's full name. */
    public static final String __NAME__ = TemplateName.DEMO_SWITCH;
    private static final com.google.template.soy.parseinfo.TemplateName __TEMPLATE_NAME__ = TemplateName.DEMO_SWITCH__NAME;

    /** The name of a kid. */
    public static final String NAME = Param.NAME;

    private DemoSwitchSoyTemplateInfo() {
      super(
          __NAME__,
          __TEMPLATE_NAME__,
          com.google.common.collect.ImmutableMap.<String, ParamRequisiteness>builder()
              .put(NAME, ParamRequisiteness.REQUIRED)
              .build());
    }

    private static final DemoSwitchSoyTemplateInfo __INSTANCE__ =
        new DemoSwitchSoyTemplateInfo();

    public static DemoSwitchSoyTemplateInfo getInstance() {
      return __INSTANCE__;
    }
  }

  /** Same as DemoSwitchSoyTemplateInfo.getInstance(). */
  @Deprecated
  public static final DemoSwitchSoyTemplateInfo DEMO_SWITCH =
      DemoSwitchSoyTemplateInfo.getInstance();


  /**
   * Demo 'for'.
   * 
   * @deprecated Use {@link com.google.template.soy.examples.FeaturesTemplates.DemoFor} instead. See go/soy-java-type-safe.
   */
  @Deprecated
  public static final class DemoForSoyTemplateInfo extends SoyTemplateInfo {

    /** This template's full name. */
    public static final String __NAME__ = TemplateName.DEMO_FOR;
    private static final com.google.template.soy.parseinfo.TemplateName __TEMPLATE_NAME__ = TemplateName.DEMO_FOR__NAME;

    /**
     * * List of persons. Each person must have
     *                                                             * 'name' and 'numWaffles'.
     */
    public static final String PERSONS = Param.PERSONS;

    private DemoForSoyTemplateInfo() {
      super(
          __NAME__,
          __TEMPLATE_NAME__,
          com.google.common.collect.ImmutableMap.<String, ParamRequisiteness>builder()
              .put(PERSONS, ParamRequisiteness.REQUIRED)
              .build());
    }

    private static final DemoForSoyTemplateInfo __INSTANCE__ =
        new DemoForSoyTemplateInfo();

    public static DemoForSoyTemplateInfo getInstance() {
      return __INSTANCE__;
    }
  }

  /** Same as DemoForSoyTemplateInfo.getInstance(). */
  @Deprecated
  public static final DemoForSoyTemplateInfo DEMO_FOR =
      DemoForSoyTemplateInfo.getInstance();


  /**
   * Demo 'for' using range.
   * 
   * @deprecated Use {@link com.google.template.soy.examples.FeaturesTemplates.DemoForRange} instead. See go/soy-java-type-safe.
   */
  @Deprecated
  public static final class DemoForRangeSoyTemplateInfo extends SoyTemplateInfo {

    /** This template's full name. */
    public static final String __NAME__ = TemplateName.DEMO_FOR_RANGE;
    private static final com.google.template.soy.parseinfo.TemplateName __TEMPLATE_NAME__ = TemplateName.DEMO_FOR_RANGE__NAME;

    /** The number of lines to display. */
    public static final String NUM_LINES = Param.NUM_LINES;

    private DemoForRangeSoyTemplateInfo() {
      super(
          __NAME__,
          __TEMPLATE_NAME__,
          com.google.common.collect.ImmutableMap.<String, ParamRequisiteness>builder()
              .put(NUM_LINES, ParamRequisiteness.REQUIRED)
              .build());
    }

    private static final DemoForRangeSoyTemplateInfo __INSTANCE__ =
        new DemoForRangeSoyTemplateInfo();

    public static DemoForRangeSoyTemplateInfo getInstance() {
      return __INSTANCE__;
    }
  }

  /** Same as DemoForRangeSoyTemplateInfo.getInstance(). */
  @Deprecated
  public static final DemoForRangeSoyTemplateInfo DEMO_FOR_RANGE =
      DemoForRangeSoyTemplateInfo.getInstance();


  /**
   * Demo 'call' without 'param's.
   * 
   * @deprecated Use {@link com.google.template.soy.examples.FeaturesTemplates.DemoCallWithoutParam} instead. See go/soy-java-type-safe.
   */
  @Deprecated
  public static final class DemoCallWithoutParamSoyTemplateInfo extends SoyTemplateInfo {

    /** This template's full name. */
    public static final String __NAME__ = TemplateName.DEMO_CALL_WITHOUT_PARAM;
    private static final com.google.template.soy.parseinfo.TemplateName __TEMPLATE_NAME__ = TemplateName.DEMO_CALL_WITHOUT_PARAM__NAME;

    /** The name of the person who took a trip. */
    public static final String NAME = Param.NAME;
    public static final String TRIP_INFO = Param.TRIP_INFO;

    // Indirect params.
    /** Listed by .tripReport_ (private). */
    public static final String DESTINATION = Param.DESTINATION;

    private DemoCallWithoutParamSoyTemplateInfo() {
      super(
          __NAME__,
          __TEMPLATE_NAME__,
          com.google.common.collect.ImmutableMap.<String, ParamRequisiteness>builder()
              .put(NAME, ParamRequisiteness.REQUIRED)
              .put(TRIP_INFO, ParamRequisiteness.REQUIRED)
              .put(DESTINATION, ParamRequisiteness.OPTIONAL)
              .build());
    }

    private static final DemoCallWithoutParamSoyTemplateInfo __INSTANCE__ =
        new DemoCallWithoutParamSoyTemplateInfo();

    public static DemoCallWithoutParamSoyTemplateInfo getInstance() {
      return __INSTANCE__;
    }
  }

  /** Same as DemoCallWithoutParamSoyTemplateInfo.getInstance(). */
  @Deprecated
  public static final DemoCallWithoutParamSoyTemplateInfo DEMO_CALL_WITHOUT_PARAM =
      DemoCallWithoutParamSoyTemplateInfo.getInstance();


  /**
   * Demo a 'call' out to a template defined in another file.
   * 
   * @deprecated Use {@link com.google.template.soy.examples.FeaturesTemplates.DemoCallOtherFile} instead. See go/soy-java-type-safe.
   */
  @Deprecated
  public static final class DemoCallOtherFileSoyTemplateInfo extends SoyTemplateInfo {

    /** This template's full name. */
    public static final String __NAME__ = TemplateName.DEMO_CALL_OTHER_FILE;
    private static final com.google.template.soy.parseinfo.TemplateName __TEMPLATE_NAME__ = TemplateName.DEMO_CALL_OTHER_FILE__NAME;

    private DemoCallOtherFileSoyTemplateInfo() {
      super(
          __NAME__,
          __TEMPLATE_NAME__,
          ImmutableMap.<String, ParamRequisiteness>of());
    }

    private static final DemoCallOtherFileSoyTemplateInfo __INSTANCE__ =
        new DemoCallOtherFileSoyTemplateInfo();

    public static DemoCallOtherFileSoyTemplateInfo getInstance() {
      return __INSTANCE__;
    }
  }

  /** Same as DemoCallOtherFileSoyTemplateInfo.getInstance(). */
  @Deprecated
  public static final DemoCallOtherFileSoyTemplateInfo DEMO_CALL_OTHER_FILE =
      DemoCallOtherFileSoyTemplateInfo.getInstance();


  /**
   * Demo 'call' with 'param's.
   * 
   * @deprecated Use {@link com.google.template.soy.examples.FeaturesTemplates.DemoCallWithParam} instead. See go/soy-java-type-safe.
   */
  @Deprecated
  public static final class DemoCallWithParamSoyTemplateInfo extends SoyTemplateInfo {

    /** This template's full name. */
    public static final String __NAME__ = TemplateName.DEMO_CALL_WITH_PARAM;
    private static final com.google.template.soy.parseinfo.TemplateName __TEMPLATE_NAME__ = TemplateName.DEMO_CALL_WITH_PARAM__NAME;

    /** The name of the person who took the trips. */
    public static final String NAME = Param.NAME;
    /**
     * The name of the person who went along for the odd-numbered
     *                                  trips only.
     */
    public static final String COMPANION_NAME = Param.COMPANION_NAME;
    /** List of destinations visited by this person. */
    public static final String DESTINATIONS = Param.DESTINATIONS;

    private DemoCallWithParamSoyTemplateInfo() {
      super(
          __NAME__,
          __TEMPLATE_NAME__,
          com.google.common.collect.ImmutableMap.<String, ParamRequisiteness>builder()
              .put(NAME, ParamRequisiteness.REQUIRED)
              .put(COMPANION_NAME, ParamRequisiteness.REQUIRED)
              .put(DESTINATIONS, ParamRequisiteness.REQUIRED)
              .build());
    }

    private static final DemoCallWithParamSoyTemplateInfo __INSTANCE__ =
        new DemoCallWithParamSoyTemplateInfo();

    public static DemoCallWithParamSoyTemplateInfo getInstance() {
      return __INSTANCE__;
    }
  }

  /** Same as DemoCallWithParamSoyTemplateInfo.getInstance(). */
  @Deprecated
  public static final DemoCallWithParamSoyTemplateInfo DEMO_CALL_WITH_PARAM =
      DemoCallWithParamSoyTemplateInfo.getInstance();


  /**
   * Demo 'call' with a 'param' block.
   * 
   * @deprecated Use {@link com.google.template.soy.examples.FeaturesTemplates.DemoCallWithParamBlock} instead. See go/soy-java-type-safe.
   */
  @Deprecated
  public static final class DemoCallWithParamBlockSoyTemplateInfo extends SoyTemplateInfo {

    /** This template's full name. */
    public static final String __NAME__ = TemplateName.DEMO_CALL_WITH_PARAM_BLOCK;
    private static final com.google.template.soy.parseinfo.TemplateName __TEMPLATE_NAME__ = TemplateName.DEMO_CALL_WITH_PARAM_BLOCK__NAME;

    public static final String NAME = Param.NAME;

    private DemoCallWithParamBlockSoyTemplateInfo() {
      super(
          __NAME__,
          __TEMPLATE_NAME__,
          com.google.common.collect.ImmutableMap.<String, ParamRequisiteness>builder()
              .put(NAME, ParamRequisiteness.REQUIRED)
              .build());
    }

    private static final DemoCallWithParamBlockSoyTemplateInfo __INSTANCE__ =
        new DemoCallWithParamBlockSoyTemplateInfo();

    public static DemoCallWithParamBlockSoyTemplateInfo getInstance() {
      return __INSTANCE__;
    }
  }

  /** Same as DemoCallWithParamBlockSoyTemplateInfo.getInstance(). */
  @Deprecated
  public static final DemoCallWithParamBlockSoyTemplateInfo DEMO_CALL_WITH_PARAM_BLOCK =
      DemoCallWithParamBlockSoyTemplateInfo.getInstance();


  /**
   * Demo {param} blocks with 'kind' attribute.
   * 
   * @deprecated Use {@link com.google.template.soy.examples.FeaturesTemplates.DemoParamWithKindAttribute} instead. See go/soy-java-type-safe.
   */
  @Deprecated
  public static final class DemoParamWithKindAttributeSoyTemplateInfo extends SoyTemplateInfo {

    /** This template's full name. */
    public static final String __NAME__ = TemplateName.DEMO_PARAM_WITH_KIND_ATTRIBUTE;
    private static final com.google.template.soy.parseinfo.TemplateName __TEMPLATE_NAME__ = TemplateName.DEMO_PARAM_WITH_KIND_ATTRIBUTE__NAME;

    /** A message text. */
    public static final String MESSAGE = Param.MESSAGE;
    /** A list of things. */
    public static final String LIST = Param.LIST;

    private DemoParamWithKindAttributeSoyTemplateInfo() {
      super(
          __NAME__,
          __TEMPLATE_NAME__,
          com.google.common.collect.ImmutableMap.<String, ParamRequisiteness>builder()
              .put(MESSAGE, ParamRequisiteness.REQUIRED)
              .put(LIST, ParamRequisiteness.REQUIRED)
              .build());
    }

    private static final DemoParamWithKindAttributeSoyTemplateInfo __INSTANCE__ =
        new DemoParamWithKindAttributeSoyTemplateInfo();

    public static DemoParamWithKindAttributeSoyTemplateInfo getInstance() {
      return __INSTANCE__;
    }
  }

  /** Same as DemoParamWithKindAttributeSoyTemplateInfo.getInstance(). */
  @Deprecated
  public static final DemoParamWithKindAttributeSoyTemplateInfo DEMO_PARAM_WITH_KIND_ATTRIBUTE =
      DemoParamWithKindAttributeSoyTemplateInfo.getInstance();


  /**
   * Demo expressions.
   * 
   * @deprecated Use {@link com.google.template.soy.examples.FeaturesTemplates.DemoExpressions} instead. See go/soy-java-type-safe.
   */
  @Deprecated
  public static final class DemoExpressionsSoyTemplateInfo extends SoyTemplateInfo {

    /** This template's full name. */
    public static final String __NAME__ = TemplateName.DEMO_EXPRESSIONS;
    private static final com.google.template.soy.parseinfo.TemplateName __TEMPLATE_NAME__ = TemplateName.DEMO_EXPRESSIONS__NAME;

    /** List of students. */
    public static final String STUDENTS = Param.STUDENTS;
    /** The current year. */
    public static final String CURRENT_YEAR = Param.CURRENT_YEAR;

    private DemoExpressionsSoyTemplateInfo() {
      super(
          __NAME__,
          __TEMPLATE_NAME__,
          com.google.common.collect.ImmutableMap.<String, ParamRequisiteness>builder()
              .put(STUDENTS, ParamRequisiteness.REQUIRED)
              .put(CURRENT_YEAR, ParamRequisiteness.REQUIRED)
              .build());
    }

    private static final DemoExpressionsSoyTemplateInfo __INSTANCE__ =
        new DemoExpressionsSoyTemplateInfo();

    public static DemoExpressionsSoyTemplateInfo getInstance() {
      return __INSTANCE__;
    }
  }

  /** Same as DemoExpressionsSoyTemplateInfo.getInstance(). */
  @Deprecated
  public static final DemoExpressionsSoyTemplateInfo DEMO_EXPRESSIONS =
      DemoExpressionsSoyTemplateInfo.getInstance();


  /**
   * Demo double braces.
   * 
   * @deprecated Use {@link com.google.template.soy.examples.FeaturesTemplates.DemoDoubleBraces} instead. See go/soy-java-type-safe.
   */
  @Deprecated
  public static final class DemoDoubleBracesSoyTemplateInfo extends SoyTemplateInfo {

    /** This template's full name. */
    public static final String __NAME__ = TemplateName.DEMO_DOUBLE_BRACES;
    private static final com.google.template.soy.parseinfo.TemplateName __TEMPLATE_NAME__ = TemplateName.DEMO_DOUBLE_BRACES__NAME;

    /** The name of the infinite set. */
    public static final String SET_NAME = Param.SET_NAME;
    /** List of the first few members of the set. */
    public static final String SET_MEMBERS = Param.SET_MEMBERS;

    private DemoDoubleBracesSoyTemplateInfo() {
      super(
          __NAME__,
          __TEMPLATE_NAME__,
          com.google.common.collect.ImmutableMap.<String, ParamRequisiteness>builder()
              .put(SET_NAME, ParamRequisiteness.REQUIRED)
              .put(SET_MEMBERS, ParamRequisiteness.REQUIRED)
              .build());
    }

    private static final DemoDoubleBracesSoyTemplateInfo __INSTANCE__ =
        new DemoDoubleBracesSoyTemplateInfo();

    public static DemoDoubleBracesSoyTemplateInfo getInstance() {
      return __INSTANCE__;
    }
  }

  /** Same as DemoDoubleBracesSoyTemplateInfo.getInstance(). */
  @Deprecated
  public static final DemoDoubleBracesSoyTemplateInfo DEMO_DOUBLE_BRACES =
      DemoDoubleBracesSoyTemplateInfo.getInstance();


  /**
   * Demo BiDi support.
   * 
   * @deprecated Use {@link com.google.template.soy.examples.FeaturesTemplates.DemoBidiSupport} instead. See go/soy-java-type-safe.
   */
  @Deprecated
  public static final class DemoBidiSupportSoyTemplateInfo extends SoyTemplateInfo {

    /** This template's full name. */
    public static final String __NAME__ = TemplateName.DEMO_BIDI_SUPPORT;
    private static final com.google.template.soy.parseinfo.TemplateName __TEMPLATE_NAME__ = TemplateName.DEMO_BIDI_SUPPORT__NAME;

    /** Book title. */
    public static final String TITLE = Param.TITLE;
    /** Author's name. */
    public static final String AUTHOR = Param.AUTHOR;
    /** Year published. */
    public static final String YEAR = Param.YEAR;
    public static final String KEYWORDS = Param.KEYWORDS;

    private DemoBidiSupportSoyTemplateInfo() {
      super(
          __NAME__,
          __TEMPLATE_NAME__,
          com.google.common.collect.ImmutableMap.<String, ParamRequisiteness>builder()
              .put(TITLE, ParamRequisiteness.REQUIRED)
              .put(AUTHOR, ParamRequisiteness.REQUIRED)
              .put(YEAR, ParamRequisiteness.REQUIRED)
              .put(KEYWORDS, ParamRequisiteness.REQUIRED)
              .build());
    }

    private static final DemoBidiSupportSoyTemplateInfo __INSTANCE__ =
        new DemoBidiSupportSoyTemplateInfo();

    public static DemoBidiSupportSoyTemplateInfo getInstance() {
      return __INSTANCE__;
    }
  }

  /** Same as DemoBidiSupportSoyTemplateInfo.getInstance(). */
  @Deprecated
  public static final DemoBidiSupportSoyTemplateInfo DEMO_BIDI_SUPPORT =
      DemoBidiSupportSoyTemplateInfo.getInstance();


  /**
   * Template that outputs -1 in a right-to-left page and 1 in a left-to-right page, i.e. basically
   * exposes the results of Soy's bidiGlobalDir() to scripts.
   * 
   * @deprecated Use {@link com.google.template.soy.examples.FeaturesTemplates.BidiGlobalDir} instead. See go/soy-java-type-safe.
   */
  @Deprecated
  public static final class BidiGlobalDirSoyTemplateInfo extends SoyTemplateInfo {

    /** This template's full name. */
    public static final String __NAME__ = TemplateName.BIDI_GLOBAL_DIR;
    private static final com.google.template.soy.parseinfo.TemplateName __TEMPLATE_NAME__ = TemplateName.BIDI_GLOBAL_DIR__NAME;

    private BidiGlobalDirSoyTemplateInfo() {
      super(
          __NAME__,
          __TEMPLATE_NAME__,
          ImmutableMap.<String, ParamRequisiteness>of());
    }

    private static final BidiGlobalDirSoyTemplateInfo __INSTANCE__ =
        new BidiGlobalDirSoyTemplateInfo();

    public static BidiGlobalDirSoyTemplateInfo getInstance() {
      return __INSTANCE__;
    }
  }

  /** Same as BidiGlobalDirSoyTemplateInfo.getInstance(). */
  @Deprecated
  public static final BidiGlobalDirSoyTemplateInfo BIDI_GLOBAL_DIR =
      BidiGlobalDirSoyTemplateInfo.getInstance();


  /**
   * Template for printing the header to add before each example.
   * 
   * @deprecated Use {@link com.google.template.soy.examples.FeaturesTemplates.ExampleHeader} instead. See go/soy-java-type-safe.
   */
  @Deprecated
  public static final class ExampleHeaderSoyTemplateInfo extends SoyTemplateInfo {

    /** This template's full name. */
    public static final String __NAME__ = TemplateName.EXAMPLE_HEADER;
    private static final com.google.template.soy.parseinfo.TemplateName __TEMPLATE_NAME__ = TemplateName.EXAMPLE_HEADER__NAME;

    /** The number of the example. */
    public static final String EXAMPLE_NUM = Param.EXAMPLE_NUM;
    /** The name of the example. */
    public static final String EXAMPLE_NAME = Param.EXAMPLE_NAME;

    private ExampleHeaderSoyTemplateInfo() {
      super(
          __NAME__,
          __TEMPLATE_NAME__,
          com.google.common.collect.ImmutableMap.<String, ParamRequisiteness>builder()
              .put(EXAMPLE_NUM, ParamRequisiteness.REQUIRED)
              .put(EXAMPLE_NAME, ParamRequisiteness.REQUIRED)
              .build());
    }

    private static final ExampleHeaderSoyTemplateInfo __INSTANCE__ =
        new ExampleHeaderSoyTemplateInfo();

    public static ExampleHeaderSoyTemplateInfo getInstance() {
      return __INSTANCE__;
    }
  }

  /** Same as ExampleHeaderSoyTemplateInfo.getInstance(). */
  @Deprecated
  public static final ExampleHeaderSoyTemplateInfo EXAMPLE_HEADER =
      ExampleHeaderSoyTemplateInfo.getInstance();


  private FeaturesSoyInfo() {
    super(
        "features.soy",
        __NAMESPACE__,
        com.google.common.collect.ImmutableList.<SoyTemplateInfo>of(
            DEMO_COMMENTS,
            DEMO_LINE_JOINING,
            DEMO_RAW_TEXT_COMMANDS,
            DEMO_PRINT,
            DEMO_AUTOESCAPE_TRUE,
            DEMO_MSG,
            DEMO_IF,
            DEMO_SWITCH,
            DEMO_FOR,
            DEMO_FOR_RANGE,
            DEMO_CALL_WITHOUT_PARAM,
            DEMO_CALL_OTHER_FILE,
            DEMO_CALL_WITH_PARAM,
            DEMO_CALL_WITH_PARAM_BLOCK,
            DEMO_PARAM_WITH_KIND_ATTRIBUTE,
            DEMO_EXPRESSIONS,
            DEMO_DOUBLE_BRACES,
            DEMO_BIDI_SUPPORT,
            BIDI_GLOBAL_DIR,
            EXAMPLE_HEADER),
        ImmutableSet.<String>of());
  }


  private static final FeaturesSoyInfo __INSTANCE__ =
      new FeaturesSoyInfo();

  public static FeaturesSoyInfo getInstance() {
    return __INSTANCE__;
  }

}
